name: flutter_test_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image:
  connectivity_plus:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed:
  freezed_annotation:
  gap:
  hooks_riverpod: ^2.3.6
  json_annotation:
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.1
dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  pedantic_mono: any

flutter:
  uses-material-design: true
